image: node:carbon

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
