const ADD_COLLECTION = "ADD_COLLECTION";
const DELETE_COLLECTION = "DELETE_COLLECTION";

const ADD_TITLE = "ADD_TITLE";
const EDIT_TITLE = "EDIT_TITLE";
const DELETE_TITLE = "DELETE_TITLE";

const ADD_ITEM = "ADD_ITEM";
const EDIT_ITEM = "EDIT_ITEM";
const DELETE_ITEM = "DELETE_ITEM";

const DELETE_ALL_COMPLETED = "DELETE_ALL_COMPLETED";

const ADD_IMAGE = "ADD_IMAGE";
const EDIT_IMAGE = "EDIT_IMAGE";
const DELETE_IMAGE = "DELETE_IMAGE";

const TOGGLE_ITEM = "TOGGLE_ITEM";
const TOGGLE_ALL_ITEM = "TOGGLE_ALL_ITEM";

const ADD_COLOR = "ADD_COLOR";
const EDIT_COLOR = "EDIT_COLOR";
const DELETE_COLOR = "DELETE_COLOR";

const ADD_COLLABORATOR = "ADD_COLLABORATOR";
const REMOVE_COLLABORATOR = "REMOVE_COLLABORATOR";

const LOG_IN = "LOG_IN";
const LOG_OUT = "LOG_OUT";
